skins.1=1
biomes.1=savanna savanna_plateau shattered_savanna shattered_savanna_plateau
skins.2=2
biomes.2=bamboo_jungle
skins.3=3
biomes.3=birch_forest birch_forest_hills tall_birch_hills tall_birch_forest old_growth_birch_forest
skins.4=4
biomes.4=cherry_grove
skins.5=5
biomes.5=nether_wastes crimson_forest basalt_deltas soul_sand_valley
skins.6=6
biomes.6=dark_forest dark_forest_hills
skins.7=7
biomes.7=jungle jungle_hills modified_jungle jungle_edge modified_jungle_edge bamboo_jungle_hills sparse_jungle
skins.8=8
biomes.8=mangrove_swamp
skins.9=9
biomes.9=taiga taiga_hills taiga_mountains wooded_mountains snowy_tundra snowy_mountains giant_tree_taiga giant_tree_taiga_hills giant_spruce_taiga giant_spruce_taiga_hills old_growth_spruce_taiga old_growth_pine_taiga windsweapt_forest
skins.10=10
biomes.10=warped_forest